// <auto-generated/>
namespace RW.Brutal
{
  using System;
  using JetBrains.Application.I18n;
  using JetBrains.DataFlow;
  using JetBrains.Diagnostics;
  using JetBrains.Lifetimes;
  using JetBrains.Util;
  using JetBrains.Util.Logging;
  using JetBrains.Application.I18n.Plurals;
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  
  public static class Strings
  {
    private static readonly ILogger ourLog = Logger.GetLogger("RW.Brutal.Strings");

    static Strings()
    {
      // Subscribes to culture change events, so detects when the user has switched to a different language or
      // locale, and adjusts the UI text and formatting to match.
      CultureContextComponent.Instance.Change.Advise(Lifetime.Eternal, args =>
      {
          var instance = args.HasNew ? args.New : null;
          if (instance != null)
          {
            ourResourceManager = new Lazy<JetResourceManager>(
              () =>
              {
                return instance
                  .CreateResourceManager("RW.Brutal.Strings", typeof(Strings).Assembly);
              });
          }
          else
          {
            ourResourceManager = null;
          };
      });
    }
    
    private static Lazy<JetResourceManager> ourResourceManager = null;
    
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static JetResourceManager ResourceManager
    {
      get
      {
        var resourceManager = ourResourceManager;
        if (resourceManager == null)
        {
          return ErrorJetResourceManager.Instance;
        }
        return resourceManager.Value;
      }
    }
    
    public static string Choice(string format, params object[] args)
    {
        var formatter = ResourceManager.ChoiceFormatter;
        if (formatter == null) return "???";
        return string.Format(formatter, format, args);
    }

    // With the Unity Rider plugin shows the warning message "Explicit string comparison is inefficient, use 
    // 'CompareTag' instead" when the code Eg. `if (gameObject.tag == "Tank")` is used.
    public static string UseCompareTagInsteadOfExplicitStringComparison => ResourceManager.GetString(
      "UseCompareTagInsteadOfExplicitStringComparison");
  }
}