name: Build

on: [ push, pull_request ]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Build-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - name: Add NuGet.config
        shell: bash
        run: |
          FEED_NAME="github"
          FEED_URL="https://nuget.pkg.github.com/RocketWerkz/index.json"
          
          # Check if the feed URL already exists
          if ! dotnet nuget list source | grep -q "$FEED_URL"; then
          echo "Adding NuGet feed: $FEED_NAME ($FEED_URL)"
          
          dotnet nuget add source --username github.user --name $FEED_NAME --password ${{ secrets.GH_PAT }} --store-password-in-clear-text "$FEED_URL"
          else
          echo "NuGet feed with URL '$FEED_URL' already exists."
          fi
      - run: ./gradlew :buildPlugin --no-daemon
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ github.event.repository.name }}.CI.${{ github.ref_name }}
          path: output
  Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Add NuGet.config
        shell: bash
        run: |
          FEED_NAME="github"
          FEED_URL="https://nuget.pkg.github.com/RocketWerkz/index.json"
          
          # Check if the feed URL already exists
          if ! dotnet nuget list source | grep -q "$FEED_URL"; then
          echo "Adding NuGet feed: $FEED_NAME ($FEED_URL)"
          
          dotnet nuget add source --username github.user --name $FEED_NAME --password ${{ secrets.GH_PAT }} --store-password-in-clear-text "$FEED_URL"
          else
          echo "NuGet feed with URL '$FEED_URL' already exists."
          fi
      - uses: actions/cache@v4
        with:
          path: |
            build/gradle-jvm
            packages
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Test-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :testDotNet --no-daemon
