name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docfx:
    uses: RocketWerkz/rw_actions/.github/workflows/deploy-docfx.yml@main
    with:
      doc-root: "docs"
    secrets:
      gh_token: ${{ secrets.GH_PAT }}