name: InputTest

on:
  workflow_dispatch:
    inputs:
      first:
        description: 'Test input for the test job'
        required: true
        default: 'default value'
      second:
        description: 'Another test input for the test job'
        type: choice
        options:
          - option 1
          - option 2
          - option 3

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - run: |
          echo "This job just exists to test the input for the test job."
          echo "Input value: ${{ github.event.inputs.first }}"
          echo "Input value: ${{ github.event.inputs.second }}"